#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  6 09:43:04 2018

@author: DanWall
"""
import math

def distFromGroupToPoint(point, group):
        """Find distance between point and group of points"""
        x = group[0][0]
        y = group[0][1]
        d = math.sqrt((x**2) + (y**2))
        if len(group) == 1:
            return d
        else:
            mid = int((len(group))/2)
            if mid == 1:
                return d
            firstHalf = group[1:mid]
            secondHalf = group[mid + 1:]
            return min(d, distFromGroupToPoint(point, firstHalf), 
                       distFromGroupToPoint(point, secondHalf))
    
def main():
    group = [[0,3], [0,2], [0,5], [0,-1], [0,-3], [1, 2], [-2, 3],
             [4, 3], [3, 1], [3, 0], [3, -1]]
    point = [2, 2]
    print(distFromGroupToPoint(point, group))
    
main()